services:
  php:
    build:
      context: ${PROJECT_PATH}
      dockerfile: Dockerfile
    container_name: ambiente-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_PATH}/public:/var/www/html
      - ${PROJECT_PATH}/vendor:/var/www/vendor
      - ${PROJECT_PATH}/app:/var/www/app
      - ${PROJECT_PATH}/app/logs:/var/log/apache2

    links:
      - db
      - memcached
    networks:
      - network

  db:
    image: mysql:latest
    container_name: mysql-php
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network

  memcached:
    image: memcached:latest
    container_name: memcached-php
    ports:
      - "11211:11211"
    command: memcached -m 64m
    networks:
      - network

  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - ${PROJECT_PATH}/certificados :/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - php
    restart: always

    environment:
      DOMAINS: '360help.localhost -> http://php:80'
      STAGE: 'local'
      FORCE_RENEW: 'false'
    networks:
      - network

networks:
  network: